<a href="https://colab.research.google.com/github/jumbokh/python_learn/blob/master/notebooks/Numpy_%E5%AF%A6%E9%A9%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy 基础:

In [2]:
import numpy as np
import math

mysqrt = [math.sqrt(x) for x in range(0,5)]
mycrt = [x**(1/3) for x in range(0,5)]

npData = np.array(mysqrt)
print("The shape:", npData.shape)
print("The dimensionality:", npData.ndim)
print("The type:", npData.dtype)

twoDarray = np.array([mysqrt, mycrt])
print("The shape:", twoDarray.shape)
print("The dimensionality:", twoDarray.ndim)
print("The type:", twoDarray.dtype)

The shape: (5,)
The dimensionality: 1
The type: float64
The shape: (2, 5)
The dimensionality: 2
The type: float64


In [3]:
zeros = np.zeros(3)
zMat = np.zeros((4,3))
ones = np.ones(3)
oMat = np.ones((3,2))
diag = np.eye(4)
rng = np.arange(5)
dm = np.diag(rng)
print(dm.shape)
zMat_re = zMat.reshape(6,2)

(5, 5)


In [4]:
A = np.random.randint(0,10, size = (3,2))
B = np.random.randint(0,10, size = (3,3,3))
C = np.random.randint(0,10, size = (3,1))
print(A**2)
print(np.sqrt(A))
print(A + C)
print(B + C)
B[:, 0:2 , 0:2 ] -= 20
print(B)

[[ 1  4]
 [36 81]
 [16 25]]
[[1.         1.41421356]
 [2.44948974 3.        ]
 [2.         2.23606798]]
[[10 11]
 [ 6  9]
 [13 14]]
[[[17 16  9]
  [ 4  4  7]
  [18 11 10]]

 [[18 11 18]
  [ 4  7  8]
  [12  9 17]]

 [[ 9 17 14]
  [ 1  6  9]
  [17 15 10]]]
[[[-12 -13   0]
  [-16 -16   7]
  [  9   2   1]]

 [[-11 -18   9]
  [-16 -13   8]
  [  3   0   8]]

 [[-20 -12   5]
  [-19 -14   9]
  [  8   6   1]]]


## 2. Numpy 应用 1：

#### 给定一个矩阵 2nx2n，将该矩阵分成四个象限(参见示例)，然后返回一个新的 2x2 矩阵，包含每个象限的平均值。
#原矩陣:
$$
  \begin{matrix}
   1 & 2 & 5 & 7 \\
   4 & 1 & 8 & 0 \\
   2 & 0 & 5 & 1 \\
   0 & 2 & 1 & 1
  \end{matrix} \tag{1}
$$
$$
  \begin{matrix}
   1 & 2 | 5 & 7 \\
   4 & 1 | 8 & 0
  \end{matrix} \tag{1}
$$
=============================
$$
  \begin{matrix}
   2 & 0 | 5 & 1 \\
   0 & 2 | 1 & 1
  \end{matrix} \tag{1}
$$

In [5]:
import numpy

# 获取初始矩阵
matrix1 = numpy.array(
    [[1, 2, 5, 7], [4, 1, 8, 0], [2, 0, 5, 1], [0, 2, 1, 1]])

# 获得矩阵维度
n = (int)(matrix1.shape[0]/2)

# 进行切片分割
res = numpy.array(
    [[matrix1[:n, :n].sum()/(n**2), matrix1[:n, n:].sum()/(n**2)], [matrix1[n:, :n].sum()/(n**2), matrix1[n:, n:].sum()/(n**2)]])
print(res)

[[2. 5.]
 [1. 2.]]


## 3. Python 标准库 itertools：

 编写函数 sum0(lst)，接受一个包含 8 个整数的列表lst。如果列表中的某些非空子集的总和返回 0，则返回 True。例如，lst=[-3, 11, 21, 5, 10, 11, 2, 1]返回 True，因为非空子集[-3, 2, 1]中数字加起来总和为 0；又如 lst=[2, 3, 4, 5, 6, 7, 8, 9]时，函数返回 False。

In [6]:
import itertools


# 定义判定是否存在组合为0函数
def sum0(lst):
    # 获取不同长度的组合
    for num in range(1, 9):
        # 获取相同长度下的不同组合迭代器
        it = itertools.combinations(lst, num)
        # 遍历判断是否和为0
        for i in it:
            if sum(i) == 0:
                return True
    return False


lst = [1, 2, 3, 4, 5, 6, 7, -28]

print(sum0(lst))

True


## Python 标准库 datetime:

####   编写函数 calculate_age，计算自出生以来到目前为止，生活的总天数，总月数，总年数，返回元组（days，months，years）；

In [8]:
import datetime


# 定义计算年龄函数
def calculate_age():

    # 将生日转为datetime
    birthday = datetime.datetime(1995, 12, 19)
    # 获取datetime当前时间
    cur = datetime.datetime.now()
    # 获得日期差
    during_days = (cur-birthday).days
    # 获得对应年月日
    return(during_days, (int)(during_days/30), (int)(during_days/365))


print(calculate_age())

(10517, 350, 28)


#### (1) 把实验、作业、小测的代码文件整理好，分开放在“作业”文件夹、“实验”文件夹、“小测”文件夹，三个文件夹放到同一个文件夹“代码”中。
#### (2) 编写函数，统计“代码”文件夹中 python 文件的个数（file_num）,写过的代码行数（ code_line ），代码中空行的行数 （ space_lines ），注释的行数 （comments_lines，只统计以#开头的），返回元组记录上述信息。

In [ ]:
import collections
import sys
import os


def getInfo(path):
    # path = './code'
    file_num = 0
    code_line = 0
    space_lines = 0
    comments_lines = 0
    if not os.path.exists(path):
        print('Invalid Path!')
        return
    # 如果是路径
    if os.path.isdir(path):
        for j in os.listdir(path):
            if j.endswith('.py'):
                file_num += 1
                for line in open(path+'/'+j, encoding='utf-8'):
                    code_line += 1
                    if line == "\n":
                        space_lines += 1
                    if line.startswith('#'):
                        comments_lines += 1
    # 如果是Python文件
    elif os.path.isfile(path) and path.endswith('.py'):
        file_num += 1
        for line in open(path, encoding='utf-8'):
            code_line += 1
            if line == "\n":
                space_lines += 1
            if line.startswith('#'):
                comments_lines += 1
    return(file_num, code_line, space_lines, comments_lines)


print(getInfo('./code/Homework'))